### ISSUE TITLE
What is the test paradigm?

### ISSUE THREAD

**Issue by chlmarchal** [Cytomine-ULiege/pims-plugin-format-openslide#1]
Hello, I would like to implement tests for the Openslide plugin. 

What would be more suitable for the location of the Openslide plugin tests? In the pims repository or the pims-plugin-format-openslide repository? 

Then, as the way the Openslide plugin has been implemented, what would be a way to test if the formats have been added in the right way thanks to the plugin? 

I think this question could be appropriate for any pims plugin that will be developed later. 

Have a nice day!

**Comment by urubens** [comment]
Hi,

Implementing tests for the plugin in the plugin repository sounds better to me to avoid to have unexpected dependencies in pims. `pims-plugin-format-openslide` requires `pims` to work (and the the tests for Openslide formats probably also need `pims`), but the inverse is not true :)

However, as all formats across plugins follow the same conventions, probably it could be a nice idea to create a format-agnostic test bed in PIMS for unit and/or integration tests. 

To test that the format checker/parser/reader is correctly doing its job, let's say for example a function `test_image_info(filepath, expected)` defined in PIMS tests. Default PIMS formats (such as tiff, jpeg, ...) tests could be located in main PIMS repository and same kind of tests in each plugin for its set of formats.

To test if the plugin is well defined and correctly read by the PIMS server at startup (is it what you mean by "test if the formats have been added the right way" ?), a simple test (implemented in the plugin) could be:
```
from pims.formats import FORMAT_PLUGINS
assert "thepluginname" in FORMATS_PLUGINS
```
(See https://github.com/Cytomine-ULiege/pims/blob/master/pims/formats/__init__.py#L135)

I hope it answers your questions, if you have other ideas, fell free to share !

**Comment by chlmarchal** [comment]
Hello, I submitted this pull request with tests for ndpi and mrxs formats:
https://github.com/Cytomine-ULiege/pims-plugin-format-openslide/pull/2
